---
title: "Coronavirus Analysis"
runtime: shiny
author: "Lorenzo Braschi"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
    orientation: rows
    # social: ["facebook", "twitter", "linkedin"]
    # source_code: embed
    vertical_layout: fill
---

```{r global, include=FALSE}

library(shiny)
# library(rvest)
library(flexdashboard)
library(glue)
library(tidyverse)
library(magrittr)
library(lubridate)
library(rmarkdown)
library(patchwork)
library(ggrepel)
library(nCov2019)

# Set colors
confirmed_color <- "purple"
active_color <- "#1f77b4"
recovered_color <- "forestgreen"
death_color <- "firebrick"

# Theme for plots

theme_set(theme_minimal()+
            theme(legend.position = "",
                  plot.title = element_text(face = "bold", colour = "grey40"),
                  strip.text.y = element_text(angle = 0),
                  plot.caption = element_text(face = "bold.italic", 
                                              colour = "grey40")
            )
)

all_ncov <- load_nCov2019(lang = "en") %>% 
  .['global'] %>% 
  tbl_df()

first_case_date <- all_ncov %>% 
  group_by(country) %>% 
  summarise(first_conf = min(time))

all_ncov %<>% 
  left_join(first_case_date) %>% 
  mutate(first_conf = as.numeric(time - first_conf)) %>% 
  select(time, first_conf, everything())

```


Summary
=======================================================================

Sidebar {.sidebar}
-------------------------------------------------------------------------------

The nCov2019 package available from [their GitHub site](https://github.com/GuangchuangYu/nCov2019) provides up-to date information about the COVID-19 epidemic. The data is focused on China, but it contains access to data from the rest of the world as well. They also provide a useful [vignette](https://guangchuangyu.github.io/nCov2019/) in which the common usage of the package is explained.

The nCov2019 package contains data for `r length(unique(all_ncov$country))` countries. 

Select one or more countries to run the analysis. 

```{r}
selectizeInput("country", options = list(maxItems = 6),
            label = strong("Select up to six countries"),
            choices = sort(unique(all_ncov$country)),
            selected = c("Italy", "Spain", 
                         "United States", "United Kingdom", 
                         "China", "South Korea"), 
            multiple = TRUE)


```

Select also a range of dates to filter the data. By default, the data range is set from the first case reported in the dataset, December 01 2019, and today,  `r format(Sys.Date(), "%B %d %Y")`. 

```{r}
dateRangeInput("daterange", label = strong("Date Range"),
               start = min(all_ncov$time),
               end = max(all_ncov$time))


checkboxInput("logaxis", label = strong("Use log axis?"), 
              value = FALSE)

checkboxInput("startconf", 
              label = strong("Start analysis from first case confirmed?"), 
              value = FALSE)

df <- reactive({
  all_ncov %>% 
    filter(country %in% input$country, 
           time >= input$daterange[1], 
           time <= input$daterange[2])
})
```


Dashboard last updated on **`r format(Sys.Date(), "%B %d %Y")`**. 


Row {data-height=100}
-----------------------------------------------------------------------

### confirmed {.value-box}

```{r}
renderValueBox({
  max_conf <- df() %>%
    filter(time == min(input$daterange[2], max(time))) %>%
    summarise(cum_confirm = sum(cum_confirm)) %>%
    pluck("cum_confirm")
  valueBox(
    value = paste(format(max_conf, big.mark = ","), "", sep = " "),
    caption = "Total confirmed cases in the countries selected to date",
    icon = "fas fa-user-md",
    color = confirmed_color
  )
})

```

### all confirmed {.value-box}

```{r}
renderValueBox({
  all_conf <- all_ncov %>%
    filter(time == min(input$daterange[2], max(time))) %>%
    summarise(cum_confirm = sum(cum_confirm)) %>%
    pluck("cum_confirm")
  valueBox(
    value = paste(format(all_conf, big.mark = ","), "", sep = " "),
    caption = "Worldwide confirmed cases to date",
    icon = "fas fa-globe",
    color = "slateblue"
  )
})

```

### death {.value-box}

```{r}
renderValueBox({
  max_dead <- df() %>% 
    filter(time == min(input$daterange[2], max(time))) %>%
    summarise(cum_dead = sum(cum_dead)) %>% 
    pluck("cum_dead")
  valueBox(
    value = paste(format(max_dead, big.mark = ","), "", sep = " "),
    caption = "Total confirmed deaths in the countries selected to date",
    icon = "fas fa-heart",
    color = death_color
  )
})
```

### all death {.value-box}

```{r}
renderValueBox({
  all_dead <- all_ncov %>%
   filter(time == min(input$daterange[2], max(time))) %>%
    summarise(cum_dead = sum(cum_dead)) %>%
    pluck("cum_dead")
  valueBox(
    value = paste(format(all_dead, big.mark = ","), "", sep = " "),
    caption = "Worldwide confirmed deaths to date",
    icon = "fas fa-skull",
    color = "darkred"
  )
})
```


Row {data-height=500}
-----------------------------------------------------------------------

### **Cumulative cases per country**

```{r}
renderPlot({
  cumplot <- df() %>%
    mutate(end_label = ifelse(time == max(time), glue("{country}: {scales::comma(cum_confirm)}"), NA))

  if (input$startconf){
    cumplot %<>% ggplot(aes(first_conf, cum_confirm, color = country))
  }else{
    cumplot %<>% ggplot(aes(time, cum_confirm, color = country))
  }

  cumplot <- cumplot +
    geom_line()+
    geom_label_repel(aes(label = end_label, fill = country),
                     nudge_x = .1,
                     nudge_y = .5,
                     size = 5,
                     color = "white",
                     show.legend = FALSE
    )+
    labs(caption = glue("Data last updated on {max(df()$time)}"))

  if (input$startconf){
    cumplot <- cumplot + labs(x = "Days elapsed since first confirmed case")
  }else{
    cumplot <- cumplot + labs(x = "Date")
  }

  
  if(input$logaxis) {
    cumplot + scale_y_log10("Log number of cases", labels = scales::comma)
  }else{
    cumplot + scale_y_continuous("Number of cases", labels = scales::comma)
  }

})

```

### **Cumulative deaths per country**

```{r}
renderPlot({
  deathplot <- df() %>% 
    mutate(end_label = ifelse(time == max(time), glue("{country}: {scales::comma(cum_dead)}"), NA))
  
  if (input$startconf){
    deathplot %<>% ggplot(aes(first_conf, cum_dead, color = country))
  }else{
    deathplot %<>% ggplot(aes(time, cum_dead, color = country))
  }
  
  
  deathplot <- deathplot +
    geom_line()+
    geom_label_repel(aes(label = end_label, fill = country),
                     nudge_x = .1,
                     nudge_y = .5,
                     size = 5,
                     color = "white",
                     show.legend = FALSE
    )+
    labs(caption = glue("Data last updated on {max(df()$time)}"))

   if (input$startconf){
    deathplot <- deathplot + labs(x = "Days elapsed since first fatality")
  }else{
    deathplot <- deathplot + labs(x = "Date")
  }

  if(input$logaxis) {
    deathplot + scale_y_log10("Log number of deaths", labels = scales::comma)
  }else{
    deathplot + scale_y_continuous("Number of deaths", labels = scales::comma)
  }
})

```

Row {data-height=300}
---------------------------------------------------------------------------

### **Speed of new cases**


```{r}
df_speed <- reactive({
  df() %>%
    arrange(country, time) %>%
    group_by(country) %>%
    mutate(
      cases_confirm = cum_confirm - lag(cum_confirm),
      cases_recover = cum_heal - lag(cum_heal),
      cases_dead = cum_dead - lag(cum_dead)
    ) %>%
    filter(!is.na(cases_confirm))
})

renderPlot({
  df_speed() %>%
    mutate(seconddif = cases_confirm - lag(cases_confirm)) %>% 
    ggplot(aes(time, cases_confirm))+
    scale_y_continuous(labels = scales::comma)+
    annotate(geom = "rect",
             xmin = input$daterange[1], xmax = input$daterange[2],
             ymin = -Inf, ymax = 0, 
             alpha = .25,
             fill = "forestgreen")+
    annotate(geom = "rect",
             xmin = input$daterange[1], xmax = input$daterange[2],
             ymin = 0, ymax = Inf, 
             alpha = .25,
             fill = "firebrick")+
    facet_grid(country~.)+
    geom_hline(yintercept = 0, color = "grey50", linetype = 2)+
    geom_line(aes(y = seconddif, color = country))+
    labs(x = "",
         y = "Diff cases", 
         title = "New cases acceleration rate")+
    theme(panel.grid = element_blank())
})



```

### **Speed of new fatalities** 

```{r}
renderPlot({
  df_speed() %>%
    mutate(seconddif = cases_dead - lag(cases_dead)) %>% 
    ggplot(aes(time, cases_dead))+
    scale_y_continuous(labels = scales::comma)+
    annotate(geom = "rect",
             xmin = input$daterange[1], xmax = input$daterange[2],
             ymin = -Inf, ymax = 0, 
             alpha = .25,
             fill = "forestgreen")+
    annotate(geom = "rect",
             xmin = input$daterange[1], xmax = input$daterange[2],
             ymin = 0, ymax = Inf, 
             alpha = .25,
             fill = "firebrick")+
    facet_grid(country~.)+
    geom_hline(yintercept = 0, color = "grey50", linetype = 2)+
    geom_line(aes(y = seconddif, color = country))+
    labs(x = "",
         y = "Diff cases", 
         title = "New fatalities acceleration rate")+
    theme(panel.grid = element_blank())
})

```






About
=======================================================================

<p style="color:red">**WORK IN PROGRESS**</p>

```{r}
# TODO: A description of the data, links, and source code for the app. 
# TODO: Link to the blog
```


<!-- **The Coronavirus Dashboard: the case of Poland** -->

<!-- This Coronavirus dashboard: the case of Poland provides an overview of the 2019 Novel Coronavirus COVID-19 (2019-nCoV) epidemic for Poland. This dashboard is built with R using the R Makrdown framework and was adapted from this [dashboard](https://www.antoinesoetewey.com/files/coronavirus-dashboard.html) by Antoine Soetewey, which in turn was inspired by this other [dashboard](https://ramikrispin.github.io/coronavirus_dashboard/){target="_blank"} by Rami Krispin. -->

<!-- **Code** -->

<!-- The code behind this dashboard is available on [GitHub](https://github.com/AntoineSoetewey/coronavirus_dashboard){target="_blank"}. -->

<!-- **Data** -->

<!-- The input data for this dashboard is the dataset available from the [`{coronavirus}`](https://github.com/RamiKrispin/coronavirus){target="_blank"} R package. Make sure to download the development version of the package to have the latest data: -->

<!-- ``` -->
<!-- install.packages("devtools") -->
<!-- devtools::install_github("RamiKrispin/coronavirus") -->
<!-- ``` -->

<!-- The data and dashboard are refreshed on a daily basis. -->

<!-- The raw data is pulled from the Johns Hopkins University Center for Systems Science and Engineering (JHU CCSE) Coronavirus [repository](https://github.com/RamiKrispin/coronavirus-csv){target="_blank"}. -->

<!-- **Contact** -->

<!-- For any question or feedback, you can [contact me](https://www.statsandr.com/contact/). More information about this dashboard can be found in this [article](https://www.statsandr.com/blog/how-to-create-a-simple-coronavirus-dashboard-specific-to-your-country-in-r/). -->

<!-- **Update** -->




<!-- *Go back to [www.statsandr.com](https://www.statsandr.com/) (blog) or [www.antoinesoetewey.com](https://www.antoinesoetewey.com/) (personal website)*. -->
